//! The behaviour model rendered as OpenSpec current-state specifications.
//!
//! `openspec/specs/<capability>/spec.md` is a continuously-maintained spec of a
//! whole system — architecturally the same artifact this tool already produces,
//! in a format another toolchain reads and validates. Emitting it means nunki
//! can bootstrap OpenSpec on a codebase that already exists, and that
//! `openspec validate --strict` becomes an external check on our own output.
//!
//! Their format is validated, not stylistic, and the rules that constrain this
//! renderer are:
//!
//! * `## Purpose` and `## Requirements` are required sections.
//! * `### Requirement: <Name>` is level 3, immediately followed by narrative
//!   text containing `SHALL` or `MUST`; an empty body is an error.
//! * `#### Scenario: <Description>` is level 4, with bolded `**WHEN**` /
//!   `**THEN**`. Bulleted WHEN/THEN lines without a Scenario header warn.
//! * There are no numeric identifiers: the header text *is* the identity,
//!   normalised and unique within the file.
//!
//! That last rule is why our identifier and our evidence travel in an HTML
//! comment rather than in the heading. Their validator tolerates it, a reader
//! sees it, and the heading stays the key their tooling matches on.
//!
//! Nothing here states more than was measured. A scenario exists because a
//! status was observed in the code, not because an endpoint usually has one.

use std::collections::BTreeMap;

use crate::behaviour::{Behaviour, Requirement};

/// One file per capability, keyed by its path under `openspec/specs/`.
pub fn render(model: &Behaviour, purpose_of: &dyn Fn(&str) -> Option<String>) -> BTreeMap<String, String> {
    let mut by_unit: BTreeMap<&str, Vec<&Requirement>> = BTreeMap::new();
    for r in &model.requirements {
        by_unit.entry(r.unit.as_str()).or_default().push(r);
    }
    by_unit
        .into_iter()
        .map(|(unit, reqs)| {
            (format!("openspec/specs/{unit}/spec.md"), capability(unit, &reqs, purpose_of(unit), model))
        })
        .collect()
}

fn capability(unit: &str, reqs: &[&Requirement], purpose: Option<String>, model: &Behaviour) -> String {
    let mut s = format!("# {unit} Specification\n\n## Purpose\n");
    match purpose {
        Some(p) if !p.trim().is_empty() => s.push_str(&format!("{}\n", p.trim())),
        // Never invent a purpose. Saying what this file is remains true.
        _ => s.push_str(&format!("The behaviour of `{unit}` as implemented, derived from its source by nunki.\n")),
    }
    s.push_str(&format!(
        "\n<!-- generated by {} from {}; every requirement below carries the lines it was read from -->\n",
        model.provenance.generator,
        model.provenance.commit.as_deref().unwrap_or("an unversioned working tree"),
    ));
    s.push_str("\n## Requirements\n");
    for r in reqs {
        s.push('\n');
        s.push_str(&requirement(r));
    }
    s
}

fn requirement(r: &Requirement) -> String {
    // The heading is the identity in this format, so it has to be the thing
    // that does not move: a method and a path are unique within a capability.
    let mut s = format!("### Requirement: {} {}\n", r.method, r.path);
    s.push_str(&format!(
        "<!-- nunki:{} evidence:{}:{}-{} -->\n",
        r.id, r.evidence.file_path, r.evidence.start_line, r.evidence.end_line
    ));

    // The narrative must contain SHALL, and must say only what was measured.
    let mut shall = format!("The system SHALL expose `{} {}`", r.method, r.path);
    if let Some(m) = &r.request_model {
        shall.push_str(&format!(", accepting `{m}`"));
    }
    if let Some(m) = &r.response_model {
        shall.push_str(&format!(", responding with `{m}`"));
    }
    if !r.auth.is_empty() {
        shall.push_str(&format!(" for callers satisfying {}", r.auth.join(" and ")));
    }
    shall.push('.');
    s.push_str(&shall);
    s.push('\n');
    if let Some(summary) = r.summary.as_deref().map(str::trim).filter(|x| !x.is_empty()) {
        s.push_str(&format!("\n{summary}\n"));
    }
    if r.path_partial {
        s.push_str("\nThe path could not be fully resolved from the source; it is recorded as read.\n");
    }

    // A scenario per status the code was observed to return. Nothing is added
    // because an endpoint conventionally has it.
    if let Some(code) = r.success_status {
        s.push_str(&format!(
            "\n#### Scenario: Request succeeds\n- **WHEN** a client calls `{} {}`\n- **THEN** the system SHALL respond `{code}`\n",
            r.method, r.path
        ));
    }
    for code in &r.error_statuses {
        s.push_str(&format!(
            "\n#### Scenario: Request fails with {code}\n- **WHEN** the conditions the handler checks for `{code}` hold\n- **THEN** the system SHALL respond `{code}`\n",
        ));
    }
    s
}
