// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package ports

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	MakeHourAvailable(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

func (siw *ServerInterfaceWrapper) MakeHourAvailable(w http.ResponseWriter, r *http.Request) {
	siw.Handler.MakeHourAvailable(w, r)
}

// HandlerFromMux registers the routes. This is where the route lives, which is
// why resolution cannot simply prefer the file it is reading: the handler is
// somewhere else entirely.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	wrapper := ServerInterfaceWrapper{Handler: si}
	r.Put("/trainer/calendar/make-hour-available", wrapper.MakeHourAvailable)
	return r
}
